# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('C', 'Client'), ('E', 'Executive')], default='E', max_length=1)),
                ('is_admin', models.BooleanField(default=False, help_text='All Executives are considered Admins, but Clients are not.', verbose_name='Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('nda_file', models.FileField(null=True, upload_to=forms.models.file_upload_path)),
                ('statement_of_work_file', models.FileField(null=True, upload_to=forms.models.file_upload_path)),
                ('consulting_agreement_file', models.FileField(null=True, upload_to=forms.models.file_upload_path)),
                ('purchase_request_file', models.FileField(null=True, upload_to=forms.models.file_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultingAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulting Agreement',
                'verbose_name_plural': 'Consulting Agreement Forms',
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=9)),
                ('location', models.CharField(max_length=100)),
                ('corporation', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Executive')),
            ],
            options={
                'verbose_name': 'NDA',
                'verbose_name_plural': 'NDA Forms',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('purpose', models.TextField()),
                ('amount', models.FloatField()),
                ('service_period', models.DateTimeField()),
                ('contract_present', models.BooleanField(default=False)),
                ('invoice_cadence_recurring', models.BooleanField(default=False)),
                ('recurring_date', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('ach', 'ACH'), ('credit', 'Credit'), ('check', 'Check'), ('abacus', 'Abacus')], max_length=6)),
                ('payment_terms_net_30', models.BooleanField(default=False)),
                ('payment_terms_receipt', models.BooleanField(default=False)),
                ('additional_notes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Executive')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Request Forms',
            },
        ),
        migrations.CreateModel(
            name='StatementOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_of_services', models.TextField()),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
                ('milestones', models.BooleanField()),
                ('deliverables', models.BooleanField()),
                ('hourly_pricing', models.BooleanField()),
                ('fixed_pricing', models.BooleanField()),
                ('milestone_pricing', models.BooleanField()),
                ('hourly_rate', models.FloatField()),
                ('fixed_rate', models.FloatField()),
                ('milestone_rate', models.FloatField()),
                ('additional_terms_of_services', models.TextField()),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Executive')),
            ],
            options={
                'verbose_name': 'Statement of Work',
                'verbose_name_plural': 'Statement of Work Forms',
            },
        ),
        migrations.AddField(
            model_name='consultingagreement',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Executive'),
        ),
        migrations.AddField(
            model_name='client',
            name='consulting_agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.ConsultingAgreement'),
        ),
        migrations.AddField(
            model_name='client',
            name='executive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Executive'),
        ),
        migrations.AddField(
            model_name='client',
            name='nda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.NDA'),
        ),
        migrations.AddField(
            model_name='client',
            name='statement_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.StatementOfWork'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
