# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160810_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractusermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='abstractusermodel',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
    ]
