# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_abstractusermodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractusermodel',
            name='token',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
