# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20160814_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractusermodel',
            name='_is_active',
            field=models.BooleanField(default=False, help_text='All Executives are active upon creation. Clients must fill out the register form before their account becomes activated.', verbose_name='Active'),
        ),
    ]
