# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20160810_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractusermodel',
            name='account_type',
            field=models.CharField(choices=[('C', 'Client'), ('E', 'Executive')], max_length=1),
        ),
        migrations.AlterField(
            model_name='abstractusermodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
