# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20160810_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractusermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='abstractusermodel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='abstractusermodel',
            name='account_type',
            field=models.CharField(choices=[('C', 'Client'), ('E', 'Executive')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='abstractusermodel',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='All Executives are considered Admins, but Clients are not.', verbose_name='Admin'),
        ),
    ]
