# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20160823_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_request_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
