# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20160810_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractusermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='consultingagreement',
            options={'verbose_name': 'Consulting Agreement', 'verbose_name_plural': 'Consulting Agreement Forms'},
        ),
        migrations.AlterModelOptions(
            name='nda',
            options={'verbose_name': 'NDA', 'verbose_name_plural': 'NDA Forms'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'Purchase Request', 'verbose_name_plural': 'Purchase Request Forms'},
        ),
        migrations.AlterModelOptions(
            name='statementofwork',
            options={'verbose_name': 'Statement of Work', 'verbose_name_plural': 'Statement of Work Forms'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
