# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_client_active_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nda',
            name='ssn',
            field=models.CharField(max_length=11),
        ),
    ]
