# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20160906_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nda',
            name='executive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Executive'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Executive'),
        ),
    ]
